---
- hosts: all
  gather_facts: false
  tasks:
     - name: "Instalando o Curl"
       command: apt-get install curl -y

     - name: "Instalando o docker"
       shell: curl -sSl https://get.docker.com | sh
       ignore_errors: yes
     - name: "Instalando o python"
       command: apt-get install python -y
       command: apt-get install python-pip -y

     - name: "Instalando o docker-py"
       command: pip install docker-py
#    - name: "Instalando docker-compose"
#      command: pip install docker-compose==1.9.0

     - name: "Subindo DB"
       docker_container:
        name: "mysql-local"
        image: ambientum/mysql:5.7
#        pull: yes
        command: sleep infinity
        volumes:
          - ./mysql:/var/lib/mysql
        ports:
          - "3306:3306"
        env:
             MYSQL_ROOT_PASSWORD=root
             MYSQL_DATABASE=projeto_docker
             MYSQL_USER=docker
             MYSQL_PASSWORD=docker

     - name: "Subindo serviço web"
       docker_container:
        name: "apache-local"
        image: ambientum/php:7.0-apache
 #       pull: yes
        command: sleep infinity
        volumes:
          - ./www/html:/var/www/app/public
        ports:
          - "8080:8080"
        links:
          - "mysql-local"
